# Generated by Django 5.1.2 on 2024-12-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_client_service_staff_payment_supporttickets_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupportTickets',
            new_name='Ticket',
        ),
    ]
