# Generated by Django 5.1.2 on 2024-12-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_supporttickets_ticket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='SupportTicket',
        ),
    ]
